### ISSUE TITLE
Panic SIGSEGV

### ISSUE THREAD

**Issue by chris-short** [genuinetools/ghb0t#13]
When running as a deployment on Kubernetes v1.14.2 I am getting a segfault in under a minute.

```
time="2019-05-24T10:16:36Z" level=info msg="Bot started for user chris-short."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x665d3d]          

goroutine 1 [running]:                                                          
main.handleNotification(0x76e740, 0xc0000464c0, 0xc00009e280, 0xc000200580, 0xc0001e3ef0, 0xb, 0x0, 0x0)                                                    
    /go/src/github.com/genuinetools/ghb0t/main.go:185 +0x23d                
main.getNotifications(0x76e740, 0xc0000464c0, 0xc00009e280, 0xc0001e3ef0, 0xb, 0x1, 0x14, 0x0, 0x0)                                                            
    /go/src/github.com/genuinetools/ghb0t/main.go:144 +0x1ae
main.main.func2(0x76e740, 0xc0000464c0, 0xc0000101a0, 0x0, 0x0, 0x0, 0x0
    /go/src/github.com/genuinetools/ghb0t/main.go:112 +0x3f9 github.com/genuinetools/ghb0t/vendor/github.com/genuinetools/pkg/cli.(*Program).run(0xc0000b4000, 0x76e800, 0xc000010d20, 0xc000010180, 0x3, 0x3, 0x4a87dd, 0x70a507)
    /go/src/github.com/genuinetools/ghb0t/vendor/github.com/genuinetools/pkg/cli/cli.go:179 +0x253 github.com/genuinetools/ghb0t/vendor/github.com/genuinetools/pkg/cli.(*Program).Run(0xc0000b4000)                           
    /go/src/github.com/genuinetools/ghb0t/vendor/github.com/genuinetools/pkg/cli/cli.go:89 +0x61                                                 
main.main()
    go/src/github.com/genuinetools/ghb0t/main.go:120 +0x34b
```

If I can provide more info lmk, please.

**Comment by chris-short** [comment]
k8s deployment is here: https://github.com/chris-short/ghb0t/blob/master/ghb0t-Deployment.yaml

**Comment by jcsims** [comment]
I've got the same issue running against a Github Enterprise instance, version 2.18.4. When I get a minute, I'll walk through the notifications that ghb0t is seeing that might cause the issue.

```sh
$ ghb0t version
ghb0t:
version     : v0.4.7
git hash    : 1d6fd2e
go version  : go1.13.4
go compiler : gc
platform    : linux/amd64
```

**Comment by jakoch** [comment]
ded project? 😕
